services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: mindforge_api
    restart: always
    environment:
      ENV: prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 15s  # <--- добавлено время для старта
    networks:
      - mindforge
    ports:
      - "8000:8000"

  bot:
    build:
      context: .
      dockerfile: docker/Dockerfile.bot
    container_name: mindforge_bot
    restart: always
    depends_on:
      api:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      ENV: prod
    networks:
      - mindforge

  redis:
    image: redis:7
    container_name: mindforge_redis
    restart: always
    networks:
      - mindforge
    ports:
      - "6380:6379"  # Используем другой порт, чтобы избежать конфликта

networks:
  mindforge:
    driver: bridge
